package com.moggot.mytranslator.translator;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DATA".
*/
public class DataDao extends AbstractDao<Data, Long> {

    public static final String TABLENAME = "DATA";

    /**
     * Properties of entity Data.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Text = new Property(1, String.class, "text", false, "TEXT");
        public final static Property Translation = new Property(2, String.class, "translation", false, "TRANSLATION");
        public final static Property InputLanguage = new Property(3, String.class, "inputLanguage", false, "INPUT_LANGUAGE");
        public final static Property OutputLanguage = new Property(4, String.class, "outputLanguage", false, "OUTPUT_LANGUAGE");
        public final static Property IsFavorites = new Property(5, Boolean.class, "isFavorites", false, "IS_FAVORITES");
    }


    public DataDao(DaoConfig config) {
        super(config);
    }
    
    public DataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TEXT\" TEXT NOT NULL ," + // 1: text
                "\"TRANSLATION\" TEXT NOT NULL ," + // 2: translation
                "\"INPUT_LANGUAGE\" TEXT NOT NULL ," + // 3: inputLanguage
                "\"OUTPUT_LANGUAGE\" TEXT NOT NULL ," + // 4: outputLanguage
                "\"IS_FAVORITES\" INTEGER);"); // 5: isFavorites
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Data entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getText());
        stmt.bindString(3, entity.getTranslation());
        stmt.bindString(4, entity.getInputLanguage());
        stmt.bindString(5, entity.getOutputLanguage());
 
        Boolean isFavorites = entity.getIsFavorites();
        if (isFavorites != null) {
            stmt.bindLong(6, isFavorites ? 1L: 0L);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Data entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getText());
        stmt.bindString(3, entity.getTranslation());
        stmt.bindString(4, entity.getInputLanguage());
        stmt.bindString(5, entity.getOutputLanguage());
 
        Boolean isFavorites = entity.getIsFavorites();
        if (isFavorites != null) {
            stmt.bindLong(6, isFavorites ? 1L: 0L);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Data readEntity(Cursor cursor, int offset) {
        Data entity = new Data( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // text
            cursor.getString(offset + 2), // translation
            cursor.getString(offset + 3), // inputLanguage
            cursor.getString(offset + 4), // outputLanguage
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0 // isFavorites
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Data entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setText(cursor.getString(offset + 1));
        entity.setTranslation(cursor.getString(offset + 2));
        entity.setInputLanguage(cursor.getString(offset + 3));
        entity.setOutputLanguage(cursor.getString(offset + 4));
        entity.setIsFavorites(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Data entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Data entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Data entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
