package com.moggot.mytranslator.translator;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TRANSLATOR".
*/
public class TranslatorDao extends AbstractDao<Translator, Long> {

    public static final String TABLENAME = "TRANSLATOR";

    /**
     * Properties of entity Translator.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Text = new Property(1, String.class, "text", false, "TEXT");
        public final static Property Translation = new Property(2, String.class, "translation", false, "TRANSLATION");
        public final static Property InputLanguage = new Property(3, String.class, "inputLanguage", false, "INPUT_LANGUAGE");
        public final static Property OutputLanguage = new Property(4, String.class, "outputLanguage", false, "OUTPUT_LANGUAGE");
        public final static Property IsFavorites = new Property(5, boolean.class, "isFavorites", false, "IS_FAVORITES");
        public final static Property Details = new Property(6, String.class, "details", false, "DETAILS");
        public final static Property Date = new Property(7, java.util.Date.class, "date", false, "DATE");
    }


    public TranslatorDao(DaoConfig config) {
        super(config);
    }
    
    public TranslatorDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TRANSLATOR\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TEXT\" TEXT NOT NULL ," + // 1: text
                "\"TRANSLATION\" TEXT NOT NULL ," + // 2: translation
                "\"INPUT_LANGUAGE\" TEXT NOT NULL ," + // 3: inputLanguage
                "\"OUTPUT_LANGUAGE\" TEXT NOT NULL ," + // 4: outputLanguage
                "\"IS_FAVORITES\" INTEGER NOT NULL ," + // 5: isFavorites
                "\"DETAILS\" TEXT," + // 6: details
                "\"DATE\" INTEGER NOT NULL );"); // 7: date
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TRANSLATOR\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Translator entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getText());
        stmt.bindString(3, entity.getTranslation());
        stmt.bindString(4, entity.getInputLanguage());
        stmt.bindString(5, entity.getOutputLanguage());
        stmt.bindLong(6, entity.getIsFavorites() ? 1L: 0L);
 
        String details = entity.getDetails();
        if (details != null) {
            stmt.bindString(7, details);
        }
        stmt.bindLong(8, entity.getDate().getTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Translator entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getText());
        stmt.bindString(3, entity.getTranslation());
        stmt.bindString(4, entity.getInputLanguage());
        stmt.bindString(5, entity.getOutputLanguage());
        stmt.bindLong(6, entity.getIsFavorites() ? 1L: 0L);
 
        String details = entity.getDetails();
        if (details != null) {
            stmt.bindString(7, details);
        }
        stmt.bindLong(8, entity.getDate().getTime());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Translator readEntity(Cursor cursor, int offset) {
        Translator entity = new Translator( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // text
            cursor.getString(offset + 2), // translation
            cursor.getString(offset + 3), // inputLanguage
            cursor.getString(offset + 4), // outputLanguage
            cursor.getShort(offset + 5) != 0, // isFavorites
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // details
            new java.util.Date(cursor.getLong(offset + 7)) // date
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Translator entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setText(cursor.getString(offset + 1));
        entity.setTranslation(cursor.getString(offset + 2));
        entity.setInputLanguage(cursor.getString(offset + 3));
        entity.setOutputLanguage(cursor.getString(offset + 4));
        entity.setIsFavorites(cursor.getShort(offset + 5) != 0);
        entity.setDetails(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setDate(new java.util.Date(cursor.getLong(offset + 7)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Translator entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Translator entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Translator entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
