package com.moggot.mytranslator.translateData;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "DATA".
 */
@Entity
public class Data {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String text;

    @NotNull
    private String translation;
    private String language;
    private Boolean isFavorites;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Data() {
    }

    public Data(Long id) {
        this.id = id;
    }

    @Generated
    public Data(Long id, String text, String translation, String language, Boolean isFavorites) {
        this.id = id;
        this.text = text;
        this.translation = translation;
        this.language = language;
        this.isFavorites = isFavorites;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getText() {
        return text;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setText(@NotNull String text) {
        this.text = text;
    }

    @NotNull
    public String getTranslation() {
        return translation;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTranslation(@NotNull String translation) {
        this.translation = translation;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public Boolean getIsFavorites() {
        return isFavorites;
    }

    public void setIsFavorites(Boolean isFavorites) {
        this.isFavorites = isFavorites;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
