package com.moggot.multipreter.translator;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "TRANSLATOR".
 */
@Entity
public class Translator {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String text;

    @NotNull
    private String translation;

    @NotNull
    private String inputLanguage;

    @NotNull
    private String outputLanguage;
    private boolean isFavorites;
    private String details;

    @NotNull
    private java.util.Date date;

    // KEEP FIELDS - put your custom fields here

    private static final String LOG_TAG = "Translator";
    // KEEP FIELDS END

    @Generated
    public Translator() {
    }

    public Translator(Long id) {
        this.id = id;
    }

    @Generated
    public Translator(Long id, String text, String translation, String inputLanguage, String outputLanguage, boolean isFavorites, String details, java.util.Date date) {
        this.id = id;
        this.text = text;
        this.translation = translation;
        this.inputLanguage = inputLanguage;
        this.outputLanguage = outputLanguage;
        this.isFavorites = isFavorites;
        this.details = details;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getText() {
        return text;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setText(@NotNull String text) {
        this.text = text;
    }

    @NotNull
    public String getTranslation() {
        return translation;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTranslation(@NotNull String translation) {
        this.translation = translation;
    }

    @NotNull
    public String getInputLanguage() {
        return inputLanguage;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setInputLanguage(@NotNull String inputLanguage) {
        this.inputLanguage = inputLanguage;
    }

    @NotNull
    public String getOutputLanguage() {
        return outputLanguage;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOutputLanguage(@NotNull String outputLanguage) {
        this.outputLanguage = outputLanguage;
    }

    public boolean getIsFavorites() {
        return isFavorites;
    }

    public void setIsFavorites(boolean isFavorites) {
        this.isFavorites = isFavorites;
    }

    public String getDetails() {
        return details;
    }

    public void setDetails(String details) {
        this.details = details;
    }

    @NotNull
    public java.util.Date getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(@NotNull java.util.Date date) {
        this.date = date;
    }

    // KEEP METHODS - put your custom methods here

    public void setTranslator(Translator translator) {
        this.id = translator.getId();
        this.text = translator.getText();
        this.translation = translator.getTranslation();
        this.inputLanguage = translator.getInputLanguage();
        this.outputLanguage = translator.getOutputLanguage();
        this.isFavorites = translator.getIsFavorites();
        this.details = translator.getDetails();
        this.date = translator.getDate();
    }
    // KEEP METHODS END

}
